# 使用轻量级 Python 镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 复制依赖文件
COPY requirements.txt /app/

# 安装 Python 依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制项目代码（包括 faust_streams.py 文件）
COPY . /app

# 声明挂载点
VOLUME /app/data

# 设置默认命令，直接运行 faust_streams.py worker
CMD ["python", "faust_streams.py", "worker"]
