FROM python:3.8-slim

# 设置工作目录
WORKDIR /app

# 安装依赖
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# 复制所有代码
COPY . /app/

# 运行 Faust Streams
CMD ["python", "faust_streams.py"]
